Make the illuminate driver threadsafe
ramonaoptics/pyilluminate pull request #16
Opened 2022-04-20 19:38 UTC by vetonsaliu8

Add re-entrant locks to methods that communicate with the illumination hardware

2022-04-20 19:40 UTC, hmaarrfk commented on pyilluminate/illuminate.py
> +    @with_thread_lock_static
do we need this? is any communication opened here?

2022-04-20 19:41 UTC, hmaarrfk commented on pyilluminate/illuminate.py
> +thread_lock = RLock()
This won't work with multiple different LED boards at the same time.

I don't think we need to lock 'static" functions. They don't use the serial port itself. They just ask the operating system for the status of the USB port.

2022-04-20 19:42 UTC, hmaarrfk requested changes
we don't need the static lock.

The second problem is that the current implementation does not enable two different LED boards to be used at the same time. 

I don't think that this is OK.

We should allow two boards to be used at the same time. The operating system will take care of the USB contention.

2022-04-20 20:04 UTC, vetonsaliu8 commented
Fixed that and other small issues.  Also added locks to fake_illuminate.

2022-04-20 21:40 UTC, hmaarrfk commented
Can you have a look at automated tests and address the failures reported please

2022-04-21 13:43 UTC, hmaarrfk commented on CHANGELOG.md
> +## 0.6.15 (2022/04/20)
```suggestion
## 0.6.15 (2022/04/20)
```

2022-04-21 13:44 UTC, hmaarrfk commented on pyilluminate/illuminate.py
> +        '_thread_lock'
```suggestion
        '_thread_lock',
```
This makes the diff smaller latter

2022-04-21 13:45 UTC, merged

2022-04-21 14:01 UTC, hmaarrfk commented
Thanks veton!